Version1.0/webDevUser15.html

webDevUser15

---

Version1.0/webDevUser23.html

b09e38716d789c065b404e20ac8e54eab9beb681

Added first line of code

---

Version1.0/webDevUser06.html

Changed name, added welcome, added made in WebDev

Jara user06

---

Version2.0/webDevUser12.html

I change something in the version two.

I user 12 

---

Version1.0/webDevUser19.html
Version2.0/webDevUser20.html

user 19 eric

---

Version4.0/user12/CSS/rainbow.css
Version4.0/user12/CSS/style.css
Version4.0/user12/portfolio.html

i add some code on protfolio page.

I user 12 shabir

---

Version4.0/user21/CSS/gallery.css
Version4.0/user21/CSS/style.css
Version4.0/user21/gallery.html

added images, 4th card, animations, font change

finished 1.4d (ben dang)

---

Version4.0/user19/CSS/style.css
Version4.0/user19/index.html

user 19 button

---

Version4.0/user14/CSS/gallery.css
Version4.0/user14/CSS/rainbow.css
Version4.0/user14/CSS/style.css
Version4.0/user14/gallery.html
Version4.0/user14/portfolio.html

EVERY assignment now, hopefully

Pulling EVERYTHING

---

Version4.0/user02/CSS/rainbow.css
Version4.0/user02/portfolio.html

unfinished 1.4 webdev02

---

Version4.0/user15/CSS/gallery.css
Version4.0/user15/CSS/style.css

Jake 15 1.4d

---

Version4.0/user23/CSS/gallery.css
Version4.0/user23/CSS/style.css
Version4.0/user23/gallery.html

I finished up Activity 1.4d CSS Animations.

User 23 | Abdifitah

---

Version4.0/user20/display.html

user 20 Quav

---

Version5.0/user01/index.html

Finished 5.0 assignment and added alot of fun things

5.0 Wyatt Osterdyk

---

Version5.0/user01/index.html

Wyatt osterdyk

---

Version5.0/user09/index.html

Added Footer used Bootstrap and Nav Bar

1.5 V3 User 09

---

Version5.0/user20/index.html

Quav user #20

---

Version5.0/user19/index.html

something afoot and i found it out

User 19 V1.5, Add files via upload

---

Version5.0/user05/index.html

You told me Activity 1.5c Navbar  and Activity 1.5c I'll Take A Menu were basically the same

Zakaria Ibrahim #5 version 5 

---

Version6.0/user23/CSS/style.css
Version6.0/user23/Manga.html
Version6.0/user23/Manhua.html
Version6.0/user23/Manhwa.html
Version6.0/user23/novels.html

Project 1.6 Your Static Website

User23 | Abdifitah

---

Version5.0/user21/index.html
Version6.0/user21/index.html

user21 - finished version 6

---

Version6.0/user16/aboutme.html
Version6.0/user16/display.html
Version6.0/user16/gallery.html
Version6.0/user16/music.html
Version6.0/user16/portfolio.html

Matthew User#16

---

Version7.0/user21/games.html
Version7.0/user21/numberguess/index.html
Version7.0/user21/numberguess/script.js

added word scramble and number guessing games

version 1.7a is finito - ben dang (user 21)

---

Version2.0/webDevUser13.html

web dev 1.2 assignment

---

Version7.0/user09/CSS/style.css
Version7.0/user09/JS/script.js
Version7.0/user09/games.html
Version7.0/user09/index.html
Version7.0/user09/script.html

I did make the button change to a stop button, then just messed around with having chat gbt make a game...

Weird Game

---

Version7.0/user11/script.html
Version7.0/user11/script.js

user 11 1.7b

---

Version7.0/user11/games.html
Version7.0/user11/index.html

user 11 7.1a

---

Version7.0/user21/JS/script.js
Version7.0/user21/JS/test.html
Version7.0/user21/index.html
Version7.0/user21/script.html

finished 1.7b - ben dang (user 21)

---

Version10Group/CSS/aboutbootstrap.html

ben dang (user 21)

---

Version10Group/CSS/Animation.html
Version6.0/user16/index.html

Matthew Lim Ver 10

---

Animation.html

Matt Ver 10

---

Version10Group/Index.html
Version10Group/aboutbootstrap.html

added more content and a little javascript is in the works

ben dang - user 21

---

Version10Group/more_javascript.html

added button hover and website layout

MoreJava_Script

---

Version10Group/aboutbootstrap.html

user 21 - ben dang

---

Version10Group/Index.html
Version10Group/table.html

I user 12 Shabir Sadeqi 

---

Version10Group/pullrequest.html

Final stuff
